ionos-cloud/crossplane-provider-ionoscloud

README.md

doc: add badges [README.md]

---

apis/k8s/v1alpha1/cluster_types.go
cluster/local/integration_tests.sh
cluster/local/integration_tests_k8s.sh
go.mod
go.sum
internal/clients/k8s/k8scluster/cluster.go
package/crds/k8s.ionoscloud.crossplane.io_clusters.yaml

This PR adds updates to the dependency SDK Go v6.0.4.
I have:

feat: update to the latest SDK Go v6.0.4

---

sonar-project.properties

This PR adds an update to the SonarCloud scan configuration to ignore the generated files.
I have:

fix: exclude generated files [SonarCloud]

---

internal/controller/compute/cubeserver/cubeserver.go
internal/controller/compute/datacenter/datacenter.go
internal/controller/compute/firewallrule/firewallrule.go
internal/controller/compute/ipblock/ipblock.go
internal/controller/compute/ipfailover/ipfailover.go
internal/controller/compute/lan/lan.go
internal/controller/compute/nic/nic.go
internal/controller/compute/server/server.go
internal/controller/compute/volume/volume.go
internal/controller/dbaas/postgrescluster/postgrescluster.go
internal/controller/k8s/k8scluster/cluster.go
internal/controller/k8s/k8snodepool/nodepool.go

fix: duplicate code for setting `ExternalClient`

---

internal/clients/compute/server/server.go
internal/utils/utils.go

This PR adds an update for the depth value.
I have:

feat: update depth value

---

.github/workflows/ci.yml
cluster/local/integration_tests.sh

This PR adds cleanup after each tests module.
I have:

fix: cleanup after each tests module

---

.github/workflows/ci.yml
Makefile

fix: update lint and submodule version

---

internal/clients/ionoscloud.go
internal/clients/ionoscloud_test.go
internal/controller/alb/applicationloadbalancer/applicationloadbalancer.go
internal/controller/alb/forwardingrule/forwardingrule.go
internal/version/version.go
tools/doc/main.go

This PR adds update for the useragent crossplane provider to contain also the version.
I have:

feat: update useragent with version

---

internal/clients/compute/server/server.go
internal/controller/compute/cubeserver/cubeserver.go

fix: check duplicate cube server

---

.github/workflows/cleanup.yml
tools/scripts/cleanup/delete-all-resources.sh
tools/scripts/cleanup/delete-backup-resources.sh
tools/scripts/cleanup/delete-compute-engine-resources.sh
tools/scripts/cleanup/delete-dbaas-resources.sh
tools/scripts/cleanup/delete-k8s-resources.sh
tools/scripts/cleanup/print-utils.sh

This PR adds a scheduled workflow to cleanup test account, which will run once a week, on Wednesdays.
I have:

feat: add cleanup workflow for test account

---

.github/workflows/cleanup.yml
tools/scripts/cleanup/delete-all-resources.sh

This PR fixes cleanup worflow.
I have:

fix: cleanup test account workflow

---

.github/workflows/ci.yml
apis/compute/v1alpha1/nic_types.go
apis/compute/v1alpha1/server_types.go
docs/CHANGELOG.md
docs/api/compute-engine/nic.md
docs/api/compute-engine/server.md
go.mod
go.sum
internal/clients/compute/nic/nic.go
internal/clients/compute/nic/nic_test.go
internal/clients/compute/server/server.go
internal/clients/compute/server/server_test.go
internal/clients/k8s/k8snodepool/nodepool.go
internal/controller/compute/server/server.go
package/crds/compute.ionoscloud.crossplane.io_nics.yaml
package/crds/compute.ionoscloud.crossplane.io_servers.yaml

- Add add `vnet` to `nic` and `placementGroupID` to `server`
- Add unit tests for server and nic.
- Small refactor to improve readability and remove duplicate code. 
This PR adds:
I have:

feat: add `vnet` to nic and `placementGroupID` to server

---

README.md
docs/CHANGELOG.md

Adds how to enable debugging and certificate pinning to crossplane using env variables. 
This PR adds:
I have:

fix: add debugging and pinning info to README.md

---

cluster/local/integration_tests_dbaas_postgres.sh

Increase dbaas psql timeout to fix daily tests.
-->
This PR adds:
I have:

fix: increase dbaas psql timeout

---

go.mod
go.sum
internal/clients/compute/nic/nic_test.go
internal/clients/k8s/k8scluster/cluster_test.go

- Should fix psql tests hopefully.
- Use generic functions.
This PR adds:
I have:

fix: bump psql to fix tests

---

examples/composition/composition.yaml

fix: composition for k8s cluster

---

Makefile

fix: make dev failure due crd too long

---

examples/server-composition/claim.yaml
examples/server-composition/composition.yaml
examples/server-composition/definition.yaml

doc: add server composition

---

package/crossplane.yaml

doc: add IONOS Cloud metadata to provider config

---

README.md
docs/README.md
docs/summary.md
examples/example.md

TWT-373 Improvements in Cross Plane Provider Documentation

---

internal/controller/serverset/bootvolume_controller.go
internal/controller/serverset/nic_controller.go
internal/controller/serverset/server_controller.go
internal/controller/serverset/serverset.go

Will be used for strategy implementation.
Fix all ilinter errors
This PR adds:
I have:

refactor: move ensure to controller

---

internal/controller/serverset/bootvolume_controller.go
internal/controller/serverset/server_controller.go

Get zone from index for server and volume
This PR adds:
I have:

feat: get zone from index

---

.github/workflows/build.yml
.github/workflows/cd.yml
.github/workflows/ci-weekly.yml
.github/workflows/ci.yml
.github/workflows/cleanup.yml
Makefile
cluster/local/integration_tests.sh

feat: update tests and dependencies of git ci action

---

apis/compute/v1alpha1/statefulserverset_types.go
apis/compute/v1alpha1/zz_generated.deepcopy.go
examples/ionoscloud/compute/statefulserverset.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml

Update Stateful Server Set

---

examples/ionoscloud/compute/statefulserverset.yaml

fix: add providerconfigref and size in gb to sss yaml

---

apis/compute/v1alpha1/lan_types.go
apis/compute/v1alpha1/statefulserverset_types.go
docs/api/compute-engine/lan.md
docs/api/compute-engine/serverset.md
examples/ionoscloud/compute/statefulserverset.yaml
go.mod
go.sum
internal/clients/compute/lan/lan.go
internal/controller/compute/lan/lan.go
internal/controller/compute/statefulserverset/datavolume_controller.go
internal/controller/compute/statefulserverset/lan_controller.go
internal/controller/compute/statefulserverset/setup.go
internal/controller/compute/statefulserverset/statefulserverset.go
internal/controller/volumeselector/volumeselector.go
package/crds/compute.ionoscloud.crossplane.io_lans.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml

ipcidrv6 added to lan CR
add lan creation, update and adding new lans to statefulserverset
This PR adds:
I have:

feat: add lan creation to statefulserverset

---

docs/api/compute-engine/statefulserverset.md
package/crds/compute.ionoscloud.crossplane.io_serversets.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml

feat: bootvolume validations and doc

---

examples/ionoscloud/compute/serverset.yaml
examples/ionoscloud/compute/statefulserverset.yaml
internal/controller/serverset/create_before_destroy.go
internal/controller/serverset/nic_controller.go

feat: create nics correctly as a list

---

examples/ionoscloud/compute/statefulserverset.yaml
internal/controller/compute/statefulserverset/datavolume_controller.go
internal/controller/compute/statefulserverset/fakes_test.go
internal/controller/compute/statefulserverset/lan_controller.go
internal/controller/compute/statefulserverset/lan_controller_test.go
internal/controller/compute/statefulserverset/objects_test.go
internal/controller/compute/statefulserverset/serverset_controller.go
internal/controller/compute/statefulserverset/statefulserverset.go
internal/controller/compute/statefulserverset/statefulserverset_test.go
internal/controller/serverset/bootvolume_controller.go
internal/controller/serverset/nic_controller.go
internal/controller/serverset/server_controller.go
internal/controller/serverset/serverset.go
internal/controller/serverset/volumeselector_controller.go
internal/controller/volumeselector/volumeselector.go

This PR adds:
- a fix related for an issue  having the IPv6cidr set to AUTO value
I have:

Fix issue with Customer Lan

---

apis/compute/v1alpha1/serverset_types.go
package/crds/compute.ionoscloud.crossplane.io_serversets.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml

Make NICs immutable

---

.github/workflows/ci.yml
apis/compute/v1alpha1/serverset_types.go
apis/compute/v1alpha1/statefulserverset_types.go
examples/ionoscloud/compute/serverset.yaml
examples/ionoscloud/compute/statefulserverset.yaml
internal/clients/ionoscloud_test.go
internal/controller/compute/statefulserverset/statefulserverset.go
internal/controller/serverset/serverset.go
internal/controller/serverset/serverset_test.go
package/crds/compute.ionoscloud.crossplane.io_serversets.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml

Add role back to the ServerSet Status

---

apis/compute/v1alpha1/serverset_types.go
internal/controller/compute/statefulserverset/serverset_controller.go
internal/controller/serverset/serverset.go
internal/controller/serverset/serverset_test.go
pkg/kube/kube.go

Populate the error message in the ServerSet Status

---

cluster/local/integration_tests_alb.sh
cluster/local/integration_tests_compute.sh
cluster/local/integration_tests_dataplatform.sh
cluster/local/integration_tests_dbaas_mongo.sh
cluster/local/integration_tests_dbaas_postgres.sh

test: change e2e tests location

---

examples/ionoscloud/compute/serverset.yaml
internal/controller/compute/statefulserverset/fakes_test.go
internal/controller/compute/statefulserverset/serverset_controller.go
internal/controller/compute/statefulserverset/statefulserverset.go
internal/controller/compute/statefulserverset/statefulserverset_test.go
internal/controller/serverset/server_controller.go
pkg/kube/kube.go

feat: sss in case of err on creation, servers should be recreated

---

internal/controller/serverset/serverset.go

feat: read master identity from status

---

apis/compute/v1alpha1/lan_types.go
apis/compute/v1alpha1/server_types.go
apis/compute/v1alpha1/volume_types.go
internal/controller/compute/cubeserver/cubeserver.go
internal/controller/compute/lan/lan.go
internal/controller/compute/server/server.go
internal/controller/compute/volume/volume.go
package/crds/compute.ionoscloud.crossplane.io_cubeservers.yaml
package/crds/compute.ionoscloud.crossplane.io_lans.yaml
package/crds/compute.ionoscloud.crossplane.io_servers.yaml
package/crds/compute.ionoscloud.crossplane.io_serversets.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml
package/crds/compute.ionoscloud.crossplane.io_volumes.yaml

feat: add name for volume, lan, server CRs

---

examples/ionoscloud/compute/statefulserverset.yaml
go.mod
go.sum
internal/controller/compute/statefulserverset/serverset_controller.go
internal/controller/serverset/serverset.go
internal/controller/serverset/serverset_test.go

Add tests for ServerSet controller Create method

---

apis/compute/v1alpha1/serverset_types.go
apis/compute/v1alpha1/statefulserverset_types.go
docs/api/compute-engine/serverset.md
docs/api/compute-engine/statefulserverset.md
examples/ionoscloud/compute/statefulserverset.yaml
internal/controller/compute/statefulserverset/lan_controller.go
internal/controller/compute/statefulserverset/lan_controller_test.go
internal/controller/compute/statefulserverset/objects_test.go
internal/controller/compute/statefulserverset/statefulserverset.go
internal/controller/serverset/nic_controller.go
internal/controller/serverset/nic_controller_test.go
internal/controller/serverset/serverset_test.go
package/crds/compute.ionoscloud.crossplane.io_serversets.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml

Populate the fields vnet, ipv4 and dhcp of the NICs
This PR adds:
I have:

Populate the NIC with vnet, ipv4 and dhcp

---

examples/local-registry.md

Example usage of local container registry
I have:

doc: local registry

---

internal/controller/serverset/bootvolume_controller.go

fix: graceful bootvolume creation on error

---

internal/controller/serverset/bootvolume_controller_test.go
internal/controller/serverset/create_before_destroy.go
internal/controller/serverset/serverset.go
internal/controller/serverset/serverset_test.go

 Add tests for ServerSet controller Update method

---

apis/compute/v1alpha1/privatecrossconnect_types.go
docs/CHANGELOG.md
docs/api/compute-engine/pcc.md
package/crds/compute.ionoscloud.crossplane.io_pccs.yaml

This PR adds:
Removes mentions of `private` in the pcc docs
I have:

doc: rename pcc in docs

---

examples/ionoscloud/dbaas/postgres-cluster.yaml
examples/ionoscloud/dbaas/postgresuser.yaml
go.mod
go.sum
internal/clients/dbaas/postgrescluster/postgrescluster.go
internal/controller/dbaas/postgresuser/postgresuser.go

This PR adds:
Fixes the issue of passwords provided via Secret appearing in cleartext
I have:

fix: pgsql user password

---

apis/compute/v1alpha1/user_types.go
package/crds/compute.ionoscloud.crossplane.io_users.yaml

fix: groupIDs optional in UserObservation

---

internal/controller/compute/statefulserverset/statefulserverset.go
internal/controller/compute/statefulserverset/statefulserverset_test.go

feat: create volumeselector if not found

---

apis/compute/v1alpha1/serverset_types.go
docs/api/compute-engine/serverset.md
docs/api/compute-engine/statefulserverset.md
package/crds/compute.ionoscloud.crossplane.io_serversets.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml

fix: remove immutable validation from nics list

---

apis/compute/v1alpha1/s3key_types.go
docs/CHANGELOG.md
docs/api/compute-engine/s3key.md
docs/api/managed-kubernetes/nodepool.md
examples/ionoscloud/compute/s3key.yaml
internal/clients/compute/s3key/s3key.go
internal/controller/compute/s3key/s3Key.go
package/crds/compute.ionoscloud.crossplane.io_s3keys.yaml
package/crds/k8s.ionoscloud.crossplane.io_nodepools.yaml

fix: save s3SecretKey and s3KeyID in secret, allow s3key deletion

---

internal/controller/serverset/serverset.go
internal/controller/serverset/serverset_test.go

fix: remove volumeselector deletion from sset

---

docs/CHANGELOG.md
internal/clients/k8s/k8snodepool/nodepool.go

fix: creation of k8s nodepool

---

apis/compute/v1alpha1/serverset_types.go
apis/compute/v1alpha1/statefulserverset_types.go
apis/compute/v1alpha1/substitutions_types.go
docs/api/compute-engine/serverset.md
docs/api/compute-engine/statefulserverset.md
package/crds/compute.ionoscloud.crossplane.io_serversets.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml

fix: improve doc and fix replica statuses shown

---

internal/controller/compute/statefulserverset/statefulserverset.go

fix: ssset lans should be deleted after nics

---

apis/compute/v1alpha1/serverset_types.go
examples/ionoscloud/compute/statefulserverset.yaml
package/crds/compute.ionoscloud.crossplane.io_serversets.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml
package/crds/compute.ionoscloud.crossplane.io_volumeselectors.yaml
package/crds/dbaas.ionoscloud.crossplane.io_postgresdatabases.yaml

fix: remove ssh key or password validation

---

cmd/provider/main.go
examples/ionoscloud/compute/statefulserverset.yaml
internal/controller/compute/statefulserverset/objects_test.go
internal/controller/compute/statefulserverset/statefulserverset.go
internal/controller/serverset/const.go
internal/controller/serverset/nic_controller_test.go
internal/controller/serverset/serverset.go
internal/controller/volumeselector/volumeselector.go

Otherwise they can go over 64 characters.
This PR adds:
I have:

fix: ssset labels need to be shorter

---

docs/CHANGELOG.md
internal/clients/k8s/k8snodepool/nodepool.go

fix: add back nodepool datacenter id fix

---

apis/compute/v1alpha1/serverset_types.go
internal/controller/serverset/recreate_only_bootvolume.go
internal/controller/serverset/serverset.go
internal/controller/serverset/serverset_test.go
package/crds/compute.ionoscloud.crossplane.io_serversets.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml

fix: ssset add hostname to status

---

cluster/local/integration_tests_k8s.sh
docs/api/compute-engine/server.md
docs/api/compute-engine/serverset.md
docs/api/compute-engine/statefulserverset.md
examples/composition/claim.yaml
examples/composition/composite.yaml
examples/composition/composition.yaml
examples/ionoscloud/compute/all.yaml
examples/ionoscloud/compute/server.yaml
examples/ionoscloud/dataplatform/dataplatformcluster.yaml
examples/ionoscloud/dataplatform/dataplatformnodepool.yaml
examples/ionoscloud/k8s/all.yaml
examples/ionoscloud/k8s/k8s-nodepool.yaml
examples/server-composition/claim.yaml
examples/server-composition/composition.yaml
internal/controller/serverset/serverset_test.go

Removed all mentions of `AMD_OPTERON` and updated Dataplatform cluster version from `23.11` to `24.3`.
I have:

fix: remove amd_opteron mentions

---

.github/workflows/cd.yml
cluster/local/integration_tests_compute.sh
internal/controller/serverset/serverset.go
internal/controller/serverset/serverset_test.go

fix: ssset ip subst should set correctly when slice changes order

---

apis/compute/v1alpha1/s3key_types.go
apis/dbaas/postgres/v1alpha1/cluster_types.go
apis/k8s/v1alpha1/cluster_types.go
apis/nlb/v1alpha1/flowlog_types.go
docs/api/compute-engine/s3key.md
docs/api/database-as-a-service/postgrescluster.md
docs/api/managed-kubernetes/cluster.md
docs/api/network-load-balancer/flowlog.md
examples/ionoscloud/compute/s3key.yaml
package/crds/compute.ionoscloud.crossplane.io_s3keys.yaml
package/crds/dbaas.ionoscloud.crossplane.io_postgresclusters.yaml
package/crds/k8s.ionoscloud.crossplane.io_clusters.yaml
package/crds/nlb.ionoscloud.crossplane.io_flowlogs.yaml

rename s3 to object storage where possible

---

cmd/provider/main.go

fix: set logger

---

internal/controller/compute/server/server.go
internal/controller/compute/statefulserverset/datavolume_controller.go
internal/controller/compute/statefulserverset/lan_controller.go
internal/controller/compute/statefulserverset/serverset_controller.go
internal/controller/serverset/bootvolume_controller.go
internal/controller/serverset/nic_controller.go
internal/controller/serverset/server_controller.go

fix: recreate datavolumes, stop continuous attachment of volume

---

README.md

enhancement: remove basic auth deprecation notice from readme

---

.github/workflows/release-upbound.yml

Try moving upbound binary to an already existing PATH instead

fix: move upbound binary to PATH

---

internal/clients/compute/server/server.go

fix: if cpu_family is not set in spec, server should not update

---

pkg/kube/kube.go

feat: ssset increase timeouts

---

docs/api/managed-kubernetes/cluster.md

fix: k8s doc

---

apis/compute/v1alpha1/firewallrule_types.go
apis/compute/v1alpha1/group_types.go
apis/compute/v1alpha1/serverset_types.go
apis/compute/v1alpha1/user_types.go
docs/api/compute-engine/firewallrule.md
docs/api/compute-engine/group.md
docs/api/compute-engine/serverset.md
docs/api/compute-engine/statefulserverset.md
docs/api/compute-engine/user.md
package/crds/compute.ionoscloud.crossplane.io_firewallrules.yaml
package/crds/compute.ionoscloud.crossplane.io_groups.yaml
package/crds/compute.ionoscloud.crossplane.io_serversets.yaml
package/crds/compute.ionoscloud.crossplane.io_statefulserversets.yaml
package/crds/compute.ionoscloud.crossplane.io_users.yaml

fix: kubebuilder default tags had wrong format

---

internal/controller/compute/statefulserverset/datavolume_controller.go
internal/controller/compute/statefulserverset/lan_controller.go
internal/controller/compute/statefulserverset/objects_test.go
internal/controller/compute/statefulserverset/serverset_controller.go
internal/controller/compute/statefulserverset/volumeselector_controller.go
internal/controller/serverset/bootvolume_controller.go
internal/controller/serverset/configmap_controller.go
internal/controller/serverset/firewallrule_controller.go
internal/controller/serverset/nic_controller.go
internal/controller/serverset/nic_controller_test.go
internal/controller/serverset/server_controller.go
internal/utils/utils.go

Add `OwnerReferences` to enable garbage collection on sub-resources of ssset and sset.
I have:

Fix: cleanup orphan resources

---

go.mod
internal/controller/compute/statefulserverset/statefulserverset.go
internal/controller/serverset/nic_controller.go

feat: parallel creation for NICS, LANS, datavolumes

---

internal/controller/serverset/nic_controller.go

fix: imports

---

Makefile
README.md
cluster/local/integration_tests_compute.sh
examples/ionoscloud/compute/server.yaml
internal/mock/clients/compute/user/user.go

fix: tests, add to docs

---

cluster/local/integration_tests_provider.sh
docs/README.md
examples/provider/debug-config.yaml
examples/provider/install-provider.yaml
internal/mock/clients/compute/user/user.go

refactor: replace ControllerConfig with DeploymentRuntimeConfig

---

apis/k8s/v1alpha1/nodepool_types.go
docs/api/managed-kubernetes/nodepool.md
examples/ionoscloud/k8s/all.yaml
examples/ionoscloud/k8s/k8s-nodepool.yaml
internal/clients/k8s/k8snodepool/nodepool.go
internal/clients/k8s/k8snodepool/nodepool_test.go
internal/controller/k8s/k8snodepool/nodepool_test.go
package/crds/k8s.ionoscloud.crossplane.io_nodepools.yaml

feat: add serverType to k8s nodepool

---

cluster/local/integration_tests_compute.sh

fix: increase update e2e timeout for volumes and lan

---

.github/workflows/cd.yml
.github/workflows/ci-weekly.yml
.github/workflows/ci.yml
.github/workflows/cleanup.yml
cluster/local/integration_tests.sh
cluster/local/integration_tests_provider.sh
cluster/local/integration_tests_statefulserverset.sh

testing: add sss e2e test, use token for testing

---

internal/clients/compute/volume/volume.go
internal/controller/compute/statefulserverset/statefulserverset_test.go
internal/controller/compute/volume/volume.go
internal/controller/compute/volume/volume_test.go

fix: update pcislot even if not 0 v1.1.13-1
