ionos-cloud/crossplane-provider-ionoscloud

- .github/workflows/build.yml
- docs/CHANGELOG.md
- docs/README.md
- internal/clients/ionoscloud.go
- internal/clients/ionoscloud_test.go
- internal/controller/compute/cubeserver/cubeserver.go
- internal/controller/dbaas/postgrescluster/postgrescluster.go
- sonar-project.properties
Use the default `IONOS_API_URL` if the creds.HostURL is empty but the variable is set. This allows to overwrite the IONOS API endpoint on a provider level additionally to "per-resource".
So the precedence is:
1. creds.HostURL
2. value of variable IONOS_API_URL set for the provider
3. The default https://api.ionos.com/
This PR adds:
I have:
> feat: Set HostURL from env variable if creds.HostURL is empty 

- internal/clients/dbaas/postgrescluster/postgrescluster.go
- internal/controller/compute/cubeserver/cubeserver.go
- internal/controller/compute/datacenter/datacenter.go
- internal/controller/compute/firewallrule/firewallrule.go
- internal/controller/compute/ipblock/ipblock.go
- internal/controller/compute/ipfailover/ipfailover.go
- internal/controller/compute/lan/lan.go
- internal/controller/compute/nic/nic.go
- internal/controller/compute/server/server.go
- internal/controller/compute/volume/volume.go
- internal/controller/dbaas/postgrescluster/postgrescluster.go
- internal/controller/k8s/k8scluster/cluster.go
- internal/controller/k8s/k8snodepool/nodepool.go
This PR updates `Delete` functions to check if apiResponse has 404 status code. This way, if the resource was deleted before, deletion is not blocked.
I have:
> fix: check apiResponse on delete

- apis/compute/v1alpha1/nic_types.go
- docs/CHANGELOG.md
- docs/api/compute-engine/nic.md
- examples/ionoscloud/compute/nic.yaml
- internal/clients/compute/nic/nic.go
- internal/controller/compute/nic/nic.go
- package/crds/compute.ionoscloud.crossplane.io_nics.yaml
This PR adds update on `mac` field from Nic Compute Resource. The field is removed from spec as it is a read-only property and it is added to the status of the resource.
I have:
> fix: remove `mac` field from Nic spec

- docs/CHANGELOG.md
- internal/clients/alb/applicationloadbalancer/applicationloadbalancer.go
- internal/clients/alb/forwardingrule/forwardingrule.go
- internal/clients/alb/targetgroup/targetgroup.go
- internal/clients/backup/backupunit/backupunit.go
- internal/clients/compute/datacenter/datacenter.go
- internal/clients/compute/firewallrule/firewallrule.go
- internal/clients/compute/ipblock/ipblock.go
- internal/clients/compute/lan/lan.go
- internal/clients/compute/nic/nic.go
- internal/clients/compute/server/server.go
- internal/clients/compute/volume/volume.go
- internal/clients/dbaas/postgrescluster/postgrescluster.go
- internal/clients/k8s/k8scluster/cluster.go
- internal/clients/k8s/k8snodepool/nodepool.go
- internal/controller/k8s/k8snodepool/nodepool_test.go
This PR adds:
- check for resources to be updated when name from IONOS Cloud is nil and `spec.forProvider.name` is not empty
- check for `spec.forProvider.name` field on `NodePool` K8s Managed Resource - for reconciliation loops
I have:
> fix: update name when upstream name is nil

- .github/workflows/ci-daily.yml
This PR adds an update on the tests run in daily workflows. Temporarily skipping ALB tests, since it is taking more than 30 minutes to create a resource.
I have:
> fix: skip ALB tests [CI daily]

- docs/CHANGELOG.md
- internal/clients/k8s/k8scluster/cluster.go
- internal/controller/k8s/k8scluster/cluster_test.go
Update the APISubnetAllowList only if not empty. Otherwise the following error message is created repeatedly:
```
Warning  CannotUpdateExternalResource  10s (x7 over 93s)  managed/cluster.k8s.ionoscloud.crossplane.io  failed to update k8s cluster. error: 422 Unprocessable Entity {
"httpStatus" : 422,
"messages" : [ {
"errorCode" : "439",
"message" : "[(root).properties.apiSubnetAllowList] The usage of 'apiSubnetAllowList' is not supported in your contract. Please contact support."
} ]
}
```
I have:
> fix: Only update APISubnetAllowList if not empty

- .github/workflows/ci-weekly.yml
Run ci weekly instead of daily.
This PR adds:
I have:
> fix: make ci run weekly instead of daily

- apis/k8s/v1alpha1/nodepool_types.go
Remove cpufamily validation from nodepools, so any type of CPU can be used.
This PR adds:
I have:
> fix: remove cpufamily validation from nodepools

- Makefile
- docs/CHANGELOG.md
- go.mod
- go.sum
- hack/helpers/addtype.sh
- hack/helpers/apis/GROUP_LOWER/APIVERSION/KIND_LOWER_types.go.tmpl
- hack/helpers/apis/GROUP_LOWER/APIVERSION/doc.go.tmpl
- hack/helpers/apis/GROUP_LOWER/APIVERSION/groupversion_info.go.tmpl
- hack/helpers/apis/GROUP_LOWER/GROUP_LOWER.go.tmpl
- hack/helpers/controller/KIND_LOWER/KIND_LOWER.go.tmpl
- hack/helpers/controller/KIND_LOWER/KIND_LOWER_test.go.tmpl
- hack/helpers/prepare.sh
- internal/features/features.go
Import from crossplane template to allow adding new types using make provider.addtype.
This PR adds:
I have:
> feat: use make provider.addtype to add new types

- internal/controller/serverset/serverset.go
- internal/controller/serverset/setup.go
Update bootvolume on template param change.
De-attach bootvolume and attach new one if one of the immutable fields changes.
Set serverset available in Observe
Wait for server to be available after attaching new volume
This PR adds:
I have:
> feat: update bootvolume, re-create if immutable attribute changes

- internal/controller/kube/kube.go
- internal/controller/serverset/conversions.go
- internal/controller/serverset/serverset.go
- internal/controller/serverset/zz_conversions.go
Move functions that use kube Client to their own file
Convert from serverset template to server, nic, volume objects to own file.
This PR adds:
I have:
> refactor: populate conversions, move functions using kube to own file

- internal/controller/serverset/bootvolume_controller.go
- internal/controller/serverset/kube.go
- internal/controller/serverset/nic_controller.go
- internal/controller/serverset/server_controller.go
- internal/controller/serverset/serverset.go
- internal/controller/serverset/setup.go
Remove kubewrapper.
Add Delete and IsResourceDeleted functions to controllers.
This PR adds:
I have:
> refactor: add delete to controllers, remove kubewrapper

- internal/controller/serverset/bootvolume_controller.go
- internal/controller/serverset/nic_controller.go
- internal/controller/serverset/server_controller.go
- internal/controller/serverset/server_controller_test.go
- pkg/ccpatch/patch_userdata.go
Add userdata tp bootvolume
Inject hostname to bootvolume
Minor fixes, use const everywhere
getZoneFromIndex - should return ZONE_1 for even, ZONE_2 for odd
This PR adds:
I have:
> feat: add userdata, inject hostname to bootvolume

- examples/ionoscloud/compute/statefulserverset.yaml
- internal/controller/compute/statefulserverset/lan_controller.go
> fix: set lan name from metadata name of template

- internal/controller/compute/statefulserverset/fakes_test.go
- internal/controller/compute/statefulserverset/serverset_controller.go
- internal/controller/compute/statefulserverset/serverset_controller_test.go
- internal/controller/compute/statefulserverset/setup.go
- internal/controller/compute/statefulserverset/statefulserverset.go
- internal/controller/compute/statefulserverset/statefulserverset_test.go
- internal/controller/compute/statefulserverset/volumeselector_controller.go
- internal/controller/serverset/const.go
- internal/controller/serverset/serverset.go
- internal/controller/serverset/setup.go
Volumeselector needs to be created in the statefulserverset, no in serverset.
This PR adds:
I have:
> feat: move volumeselector to ssset

- apis/compute/v1alpha1/server_cube_types.go
- docs/CHANGELOG.md
- docs/api/compute-engine/cubeserver.md
- examples/ionoscloud/compute/cubeserver.yaml
- internal/clients/compute/server/server.go
- internal/controller/compute/cubeserver/cubeserver.go
- package/crds/compute.ionoscloud.crossplane.io_cubeservers.yaml
This PR adds:
Fixes creation of cube servers by removing the unnecessary `cpuFamily` field
I have:
> Fix: Cube server creation

- internal/controller/serverset/serverset_test.go
> Add tests for ServerSet controller Delete method 

- docs/CHANGELOG.md
- examples/ionoscloud/dbaas/mongouser.yaml
- internal/clients/dbaas/mongo/cluster.go
- internal/controller/dbaas/mongocluster/mongoluster.go
- internal/controller/dbaas/mongouser/mongouser.go
- internal/controller/dbaas/postgresuser/postgresuser.go
This PR adds:
For `MongoUser` managed resource:
-   Fixes issues with password being stored as plain text in the resource Spec even if provided via Secret
-   Fixes panic caused by nil pointer deref
- ## Checklist
I have:
> fix: mongo user credentials

- package/crossplane.yaml
This PR adds:
Allows the provide to be installed with pre-release crossplane versions, such as 1.16.0-rc.1
I have:
> fix: allow pre-release crossplane versions

- apis/k8s/v1alpha1/nodepool_types.go
- docs/CHANGELOG.md
- internal/clients/k8s/k8snodepool/nodepool.go
- package/crds/k8s.ionoscloud.crossplane.io_nodepools.yaml
This PR adds:
Adds the `datacenterID` field to the k8s NodePool CRD
I have:
> feat: add datacenterId field to node pool lan

- internal/clients/compute/nic/nic.go
- internal/clients/compute/nic/nic_test.go
This PR adds:
Added missing ipv6 NIC property as document in https://api.ionos.com/docs/cloud/v6/#tag/Network-interfaces/operation/datacentersServersNicsPost
No changes in the CRD are required as ips are internally converted to ipv4 (ips) / ipv6 (ipv6Ips) fields required by the cloud API.
I have:
> Fix: add missing ipv6 nic property

- cluster/local/integration_tests_compute.sh
- docs/CHANGELOG.md
INTEL_XEON no longer supported in de/fra
This PR adds:
I have:
> fix: use INTEL_ICELAKE for compute e2e tests

- docs/CHANGELOG.md
- internal/controller/compute/server/server.go
> fix: slow volume attach to server

- internal/controller/compute/server/server.go
I noticed that despite increasing the max-reconcile-rate flag the number of workers assigned to each resource was remaining at 1, and that the max-reconcile-rate was only actually being used to adjust the GlobalRateLimiter (relevant P.S below). This also appears to be the case for all the other resources as well but I haven't been having scaling problems with those resources so didn't wish to over complicate the PR.
P.S I don't think the global rate limiter is being used either as the line underneath the one this PR adds just instantiates a new rate limiter with default settings)
This PR adds:
Minor code change that requires no documentation / test changes
I have:
> fix(server setup): Added MaxConcurrentReconciles to server manager setup

- .github/workflows/release-upbound.yml
Adds a workflow to release tags to Upbound
> feat: add upbound release workflow

- .github/workflows/release-upbound.yml
Fixes the upbound release workflow by using a non-deprecated way of adding binaries to path
> fix: use GITHUB_PATH instead of add-path

- docs/CHANGELOG.md
- internal/controller/k8s/k8scluster/cluster.go
- internal/controller/k8s/k8scluster/cluster_test.go
> fix: write kubeconfig if not in deploying

- apis/compute/v1alpha1/s3key_types.go
- internal/clients/compute/s3key/s3key.go
- internal/controller/compute/s3key/s3Key.go
- package/crds/compute.ionoscloud.crossplane.io_s3keys.yaml
Fix for https://github.com/ionos-cloud/crossplane-provider-ionoscloud/issues/288
I have:
> fix: s3 key stuck in creation loop after resource external delete

- docs/api/compute-engine/s3key.md
- docs/api/compute-engine/serverset.md
- docs/api/compute-engine/statefulserverset.md
- docs/api/database-as-a-service/mongouser.md
- docs/api/database-as-a-service/postgresdatabase.md
- docs/api/database-as-a-service/postgresuser.md
- docs/api/dataplatform/dataplatformcluster.md
- docs/api/dataplatform/dataplatformnodepool.md
- tools/doc/main.go
> docs: allow resource exclusion from docs generation

- cmd/provider/main.go
- internal/controller/serverset/create_before_destroy.go
- internal/controller/serverset/firewallrule_controller.go
- internal/controller/serverset/nic_controller.go
- internal/controller/serverset/server_controller.go
- internal/controller/serverset/serverset.go
- internal/controller/serverset/serverset_test.go
Increased root ctx timeout from 30m to 1h.
Refactored sset ensure functions to implement an additional check for empty serverID after server creation.
I have:
> Fix: unpredictable ssset creation and deletion behavior due to root ctx expiring

- internal/clients/k8s/k8snodepool/nodepool.go
This PR adds:
Fixes https://github.com/ionos-cloud/crossplane-provider-ionoscloud/issues/296
I have:
> fix: do not trigger update on node count when nodepool autoscaling happens

- internal/controller/compute/statefulserverset/datavolume_controller.go
- internal/controller/compute/statefulserverset/fakes_test.go
- internal/controller/compute/statefulserverset/lan_controller.go
- internal/controller/compute/statefulserverset/serverset_controller.go
- internal/controller/compute/statefulserverset/statefulserverset.go
- internal/controller/serverset/bootvolume_controller.go
- internal/controller/serverset/firewallrule_controller.go
- internal/controller/serverset/nic_controller.go
- internal/controller/serverset/server_controller.go
- internal/utils/utils.go
- pkg/kube/kube.go
> fix: delete crd sub-resources only on 422. do not delete ss, update it

- internal/controller/compute/volume/volume.go
When there are provisioning errors the pcislot can change in some edge cases. We need to re-update the vnetid in those cases.
This PR adds:
I have:
> fix: update pcislot even if it is not 0
